export const tokens = {
  colors: {
    sage: "#8B9E8B",
    sageLight: "#A7B8A7",
    sageDark: "#6B7E6B",
    sageMuted: "#D4DDD4",
    terracotta: "#C4896B",
    terracottaLight: "#D4A68B",
    terracottaDark: "#A66E52",
    sand: "#D4C5A9",
    sandLight: "#E8DCC8",
    sandDark: "#B5A78C",
    cream: "#F5F0E8",
    creamWarm: "#FAF5ED",
    earth: "#4A4239",
    earthLight: "#6B6358",
    earthMuted: "#8B8478",
  },
  spacing: {
    xs: "0.5rem",
    sm: "1rem",
    md: "1.5rem",
    lg: "2rem",
    xl: "3rem",
    "2xl": "4rem",
    "3xl": "6rem",
    "4xl": "8rem",
  },
  radii: {
    sm: "0.5rem",
    md: "1rem",
    lg: "1.5rem",
    xl: "2rem",
    organic: "2.5rem",
  },
} as const;
